### ISSUE TITLE
Mockup to show installed keptn services and latest version available

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1280]
**Idea:** Within the Keptn Bridge, the installed Keptn services (e.g., lighthouse, gatekeeper, ...) should be listed. This listing shows the latest version of each service. 

This could mean that we need to list all Kubernetes Deployments within the Keptn Namespaces, parse the images and the tags used, and verify if a newer release is available (e.g., via DockerHub, GitHub, via a JSON file that we put on our S3 Bucket, ...)

**Comment by johannes-b** [comment]
I would like to refine this issue with the underlying user-story and a mock. 

**User story**
As a user, I would like to see all Keptn-services that communicate with the control-plane on a per-project basis. Next to details like the service name, current version, and cluster/namespace this service is running, I would like to see the subscriptions this service has and configuration the service requires (on that subscription).

**Mockup**
A first mock of this view is given here: (Please note that this is still in progress)
![image](https://user-images.githubusercontent.com/729071/110469911-81923280-80da-11eb-8578-2612bdb629af.png)

**Goals of this issue:** 
- Provide a first implementation of the mockup in the Keptn Bridge. 
- This implementation is hidden behind a feature flag / URL param. 
- The data layer is mocked, meaning that the components show data from a pre-defined static data set

**Tasks**
- [ ] Implement the main component that represents this view (Uniform - beta) 
- [ ] Add a **Table** to the view that lists the Keptn-services and their details
- [ ] When clicking on a Keptn-service, the details are shown below 
- [ ] Add a component for **Subscriptions**
- [ ] **Research:** How should Subscriptions and their configuration be displayed? Idea: it is also possible to define multiple Subscriptions on the same "topic" (e.g., deployment.triggered)
- [ ] Implement the derived approach (for displaying subscriptions + config) in the mockup

**Comment by johannes-b** [comment]
As indicated by the above mockup, the component for the subscription/config part needs some rework. My current proposal is: 

![image](https://user-images.githubusercontent.com/729071/110626786-735b1980-81a1-11eb-8d29-c8beb23f35e3.png)

Thoughts/ideas/feedback is welcome.

**Comment by johannes-b** [comment]
Updated Mockup: 

![image](https://user-images.githubusercontent.com/729071/111763009-f49d6500-88a1-11eb-8d53-5bfaf6ed9467.png)
