### ISSUE TITLE
Expose /event endpoint from mongodb-datastore to the public Keptn API 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1791]
Like the configuration-service exposes its API to the public Keptn API, the mongodb-datastore should do the same for its /event endpoint.

**Tasks:**

* The `/event` endpoint in the API has to be marked as deprecated. (Do not delete the implementation of the endpoint, as we don't want to introduce a breaking change.)
```
    get:
      tags:
        - Event
      deprecated: true
      summary: 'Deprecated endpoint - please use /mongodb-datastore/v1/event'
```
* Re-configure the mongodb-datastore swagger-ui, to be exposed on the public api-gateway.

* *Investigation:* Ist the `/logs` endpoint still needed? If not, it has to be removed.

**Definition of Done**
- [ ] The `/event` endpoint of the API is marked as deprecated: https://github.com/keptn/keptn/blob/master/api/swagger.yaml#L52
- [ ] The `/event` endpoint is available when selecting the mongodb-datastore in the drop-down of the Keptn swagger UI and can be used.
![image](https://user-images.githubusercontent.com/729071/81943918-4929e100-95fc-11ea-8688-efd113be1561.png)
- [ ] Update of the keptn/docs: https://keptn.sh/docs/develop/reference/api/#explore-the-keptn-api
- [ ] The `/logs` endpoint is deleted (if not needed)
