### ISSUE TITLE
Research: Manage and retrieve test.start events via API 

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1822]
**Research Motivation:**
The goal of this research is to implement a prototype for splitting the control- and execution-plane using the `jmeter-service` as an example service.

Therefore, the following tasks need to be conducted:

**Tasks:**
- [x] go-utils: Introduce a new `test.triggered` event, which contains the same data as a `deployment.finished` event.
- [x] `mongodb-datastore`: Introduce a new collection which stores all `test.triggered` events until a corresponding `test.finished` event is received. More precisely, when a `test.triggered` event is received, it is added in the collection. When a `test.finished` event is received, the corresponding `test.triggered` event is removed from the collection.
- [x] `mongodb-datastore`: Introduce an endpoint `/event/open` which allows retrieving all open `test.triggered` events. In order to specify the event type, a query parameter can be used.
- [x] keptn-poll-sidecar: Implement a sidecar which cyclically polls the `mongodb-datastore` for open `test.triggered` events and forward those events to the `jmeter-service`. Note that the `jmeter-service` must receive an event only once. Hence, the sidecar needs to store already forwarded events.
- [x] `jmeter-service`: Add in `test.finished` event the corresponding ID of the triggered event.
- [x] `jmeter-service`: React on `test.triggered` events (adapt marshaling).
- [x] `jmeter-service`: Use the public API and an `x-token` in order to access the `configuration-service` as well as the `event-broker`.

**Definition of Done:**
- [x] Start `jmeter-service` and its sidecar in a different cluster and start a test using the CLI command `keptn send event --file=test.triggered.json`

**Comment by agrimmer** [comment]
The research is completed and the branch https://github.com/keptn/keptn/tree/feature/1822/add-test-triggered-in-mat-view contains our results.
