### ISSUE TITLE
Test and documentation on running Keptn on K3s

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1896]
The Keptn full installation use-case needs to be verified on a [K3s](https://k3s.io/) installation. 

**How-to:**

* K3s Installation (Ubuntu) -> Kubernetes 1.18:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=stable INSTALL_K3S_SYMLINK="skip" K3S_KUBECONFIG_MODE="644" sh -
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
```

* Keptn Install (quality-gates):
```
keptn install --platform=kubernetes --use-case=quality-gates --gateway=NodePort
```

* Keptn Install (full):
```
keptn install --platform=kubernetes --gateway=NodePort
```

**Tasks:**
* Implementation of an integration test with K3s - executed by Travis-CI
* Update of keptn/docs: [Keptn install](https://keptn.sh/docs/develop/operate/install/#install-keptn) to provide the instructions for a K3s installation

**Definition of Done:**
- [x] Keptn on K3s successfully tested on local machine
- [x] Integration tests using travis-ci implemented (at least for quality-gates; if possible also for full installation, but this will likely fail due to memory limits of travis-ci) 
- [x] Install documentation is up-to-date
- [ ] Support matrix updated

**Comment by christian-kreuzberger-dtx** [comment]
I tested this and here are my findings:

* `--gateway=NodePort` is required, as long as traefik (an ingress controller) is automatically started with K3s (there is an option to disable this, but it is a bit complicated in my opinion)
* Full installation and quality-gates installation seems to work fine
* Both, helm and istio seem to work okay (at least with the onboarded carts example)
* Installing dynatrace-service + oneagent takes 2 minutes to start (though this might be unrelated)
* Exposing Keptn Bridge works

**Comment by christian-kreuzberger-dtx** [comment]
Related PRs:
* https://github.com/keptn/keptn.github.io/pull/559
* #1897

**Comment by christian-kreuzberger-dtx** [comment]
I'm closing this issue, as it has been implemented. The last part of the docs update is in PR https://github.com/keptn/keptn.github.io/pull/565
