### ISSUE TITLE
Keptn CLI create command: `keptn delete service`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2198]
As a Keptn user, I would like to delete a service by executing the following command: 
```
keptn delete service carts --project sockshop
```

**Tasks:**

- Introduce the command: `keptn delete service SERVICE_NAME --project=PROJET_NAME`
    - `--project` is mandatory
- Check the number of arguments and flags. 
- The command calls the: `DELETE` endpoint in the api-service: `/project/{projectName}/service/{serviceName}` (as implemented in #2199) 

**Definition of Done:**

- [x] `keptn delete service` successfully removes a service from a Keptn project (when #.... is implemented) 
- [x] Unit tests are provided to test the new CLI command
- [ ] The flags of the command are described and an example is given (in the code) To make sure to get the documentation when generating the docs.
