### ISSUE TITLE
Switch to CloudEvents spec v1.0, remove eventbroker

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#2254]
Keptn currently utilizes CloudEvents in version 0.2. This issue upgrades the CloudEvents to version 1.0

**Tasks:**
- Upgrade https://github.com/cloudevents/sdk-go to version 2.2.0 in all services using CloudEvents
- cli: Switch to CloudEvents 1.0
- api-service, configuration-service, mongodb-datastore: adapt swagger models to be CloudEvents v1.0 conform
- distributor: **Directly** send CloudEvent to NATS or to the Keptn API
- gatekeeper-service, helm-service, jmeter-service, lighthouse-service,  openshift-route-service, remediation-service, shipyard-service: Send/receive CloudEvents v1.0 and send it to the distributor
- Remove `eventbroker`
- Update spec and documentation

**Definition of Done:**
- [ ] CLI upgraded
- [ ] api-service upgraded
- [ ] configuration-service upgraded
- [ ] mongodb-datastore upgraded
- [ ] distributor upgraded
- [ ] gatekeeper-service upgraded,
- [ ] helm-service upgraded
- [ ] jmeter-service upgraded
- [ ] lighthouse-service upgraded
- [ ] openshift-route-service upgraded
- [ ] remediation-service upgraded
- [ ] shipyard-service upgraded
- [ ] eventbroker removed
- [ ] All CloudEvents within Keptn are v1.0 conform
- [ ] Documentation is updated correspondingly

**Comment by johannes-b** [comment]
This issue is related to https://github.com/keptn/keptn/issues/1178
