### ISSUE TITLE
Integration page for guiding a Keptn user to get started

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2429]
As a user, I would like to get guidance in getting started using the CLI/API with basic examples:

![image](https://user-images.githubusercontent.com/729071/94651904-76500500-02f9-11eb-8346-47550a9114d7.png)

**Task:**
- [x] Add the menu item: `Integration`
- [x] Commit the content file (content see below) on: https://github.com/keptn/get.keptn.sh
- [x] When clicking on the menu item `Integration`, show the Keptn CLI/API part per default. 
- [x] Enable/Disable feature with a feature flag and show reference to keptn.sh/doc to inform the user about the data collected by this feature --> disable it by default
- [x] If the feature flag is enabled, load the content file (html) and display it as shown above.
- [x] If the feature flag is disabled or the call to the externally hosted file is not possible, show a link to the keptn.sh/docs as default
- [x] Make the URL to the content file customizable

# Content:
(Use https://markdowntohtml.com/ to convert the Markdown to HTML)

---
Integrate Keptn using the [Keptn CLI](https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_auth/) or [Keptn API](https://keptn.sh/docs/0.7.x/reference/api/). 

## Keptn CLI:
1. Download CLI from user menu (see top right corner)
1. Authenticate CLI with: [keptn auth](https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_auth/)

Example: 
  - Trigger a quality gate evaluation: 
  ```console
  keptn send event start-evaluation 
    --project= --stage= --service= 
    --start=2020-12-31T11:59:59 --timeframe=5m 
  ```

## Keptn API: 
1. Copy API token from user menu (see top right corner)
1. Access Keptn API

Example: 
  - Trigger a quality gate evaluation: 
  ```console
  curl -X POST "${KEPTN_API_ENDPOINT}/v1/project/{PROJECT}/stage/{STAGE}/service/{SERVICE}/evaluation" \
-H "accept: application/json; charset=utf-8" \ 
-H "x-token: ${KEPTN_API_TOKEN}" \
-H "Content-Type: application/json; charset=utf-8" \
-d "{ \"start\": \"2020-09-28T07:00:00\", \"timeframe\": \"5m\", \"labels\":{\"buildId\":\"build-17\",\"owner\":\"JohnDoe\",\"testNo\":\"47-11\"}}"
  ```

## Custom Integrations on Keptn Sandbox
- Azure DevOps Keptn Integration: [GitHub](https://github.com/keptn-sandbox/keptn-azure-devops-extension) | [Tutorial](https://tutorials.keptn.sh/tutorials/keptn-azure-devops/index.html?)
- GitLab: [GitHub](https://github.com/keptn-sandbox/gitlab-service) 
- Jenkins: [GitHub](https://github.com/keptn-sandbox/jenkins-tutorial)

---
