### ISSUE TITLE
Upgrader for migrating from Shipyard v0.1 to Shipyard v0.2

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2500]
When upgrading to Keptn 0.8, the shipyard has to be converted from v0.1 to v0.2. 

*Research:* Can this migration step be part of the `helm upgrade` command? 
 - Using `helm upgrade` for this step is not the best way because you don`t know which shipyard could not be converted in case of a failure.  --> Going with a CLI approach is more reliable. 

Upgrade path: Find here more information about the upgrade path: https://github.com/keptn/enhancement-proposals/blob/5093867408a210c728478554205df06af350b521/text/0006-shipyard-next-generation.md#upgrade-path-from-shipyard-012--to-020 

**Usage:**
```
keptn upgrade project sockshop --shipyard --fromVersion=0.1 --toVersion=0.2

Shipyard of project sockshop: 
-----------------------------------------
stages:
- name: "dev"
  deployment_strategy: "direct"
  test_strategy: "functional"
...

Shipyard converted into version 0.2:
-----------------------------------------
---
version: 0.2.0
kind: Shipyard
metadata:
  name: shipyard
spec:
  stages:
  - name: "dev"
    sequences:
...
-----------------------------------------

Do you want to upgrade project <sockshop> with the Shipyard in version 0.2 (yes/no)? : y
```

**Tasks:**
- Provide the Ketpn CLI command: `keptn upgrade project <PROJECTNAME> --shipyard --fromVersion=0.1 --toVersion=0.2`
  - `--shipyard`: Defines that an upgrade of the Shipyard file should happen
  - `--fromVersion` The current version of the Shipyard (this information is missing in the current keptn/sepc:0.1.6)
  - `--toVersion`: The target version the Shipyard has to be converted to
  - `-y`: Allows to automatically confirm.
- Implementation of the routine that reads a v0.1 Shipyard (https://github.com/keptn/spec/blob/0.1.6/shipyard.md) and converts it to v0.2 Shipyard (https://github.com/keptn/spec/pull/36/files) 
- When running this command, it reads the Shipyard from the project, converts it to version 0.2, asks for approval, and updates the project repo (just on master). 
- If it is not possible to convert the Shipyard, inform the user how to manually do this step. 

**Definition of Done:** 
- [x] A user can use the `keptn upgrade project` command to migrate to Shipyard v0.2
- [x] Documentation how to use this feature is provided on: keptn.sh/docs/0.8.x/operate/upgrade
- [x] `keptn upgrade` displays: `please upgrade your projects using keptn upgrade project`
