### ISSUE TITLE
Using new Keptn CloudEvents in keptn/contrib (and keptn/sandbox) services

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2501]
This is a meta-issue with the goal of achieving the demo-ability of the control plane by its supporting Keptn-services (running in the execution plane).

When working on this issue, individual issues in the corresponding repository in keptn-contrib (keptn-sandbox) are created. However, this issue keeps track of the progress. 

### Keptn-service template

Support new types of events in keptn-sandbox/keptn-service-template-go:
- Release v0.1.0 of: https://github.com/keptn-sandbox/keptn-service-template-go (current state) to have a 0.7.x compatible template
- Update: https://github.com/keptn-sandbox/keptn-service-template-go to support the new event format and force the steps of sending started/finished events.

**Definition of Done:** 
- [x] keptn-sandbox/keptn-service-template-go runs on v0.8: https://github.com/keptn-sandbox/keptn-service-template-go/issues/20 (@christian-kreuzberger-dtx)

### Keptn-contrib services 
File PRs to make github.com/keptn-contrib services compatible with v0.8:

- [x] dynatrace-service:
  - [x] Update Service to use CloudEvents 1.0: https://github.com/keptn-contrib/dynatrace-service/issues/181
  - [x] Adapt to next-gen Events sent by Keptn: https://github.com/keptn-contrib/dynatrace-service/issues/203
  - [x] Use new shipyard-controller Endpoint to create Services in Keptn: https://github.com/keptn-contrib/dynatrace-service/issues/202
- [x] dynatrace-sli-service (when not already merged into dynatrace-service):
  - [x] Update Service to use CloudEvents 1.0: https://github.com/keptn-contrib/dynatrace-sli-service/issues/75
  - [x] React on a triggered event with a started and finally finished event https://github.com/keptn-contrib/dynatrace-sli-service/issues/102
- [x] unleash-service:
  - [x] Update Service to use CloudEvents 1.0: https://github.com/keptn-contrib/unleash-service/issues/20
- [x] prometheus-service:
  - [x] Update Service to use CloudEvents 1.0: https://github.com/keptn-contrib/prometheus-service/issues/63
- [x] prometheus-sli-service (when not already merged into prometheus-service):
   - [x] Update Service to use CloudEvents 1.0: https://github.com/keptn-contrib/prometheus-sli-service/issues/36
   - [x] React on a triggered event with a started and finally finished event https://github.com/keptn-contrib/prometheus-sli-service/issues/44
- [ ] notification-service:
    - [ ] Update Service to use CloudEvents 1.0: https://github.com/keptn-contrib/notification-service/issues/24
- [x] argo-service:
  - [x] Update Service to use CloudEvents 1.0: https://github.com/keptn-contrib/argo-service/issues/12
- [ ] servicenow-service - is this 0.7 ready? :
- [ ] neoload-service (neoload-sli-provider) - is this 0.7 ready? : 

**Definition of Done:** 
- [ ] The services in keptn-contrib run on v0.8

### Keptn-sandbox services 
File PRs to make github.com/keptn-sandbox services compatible with v0.8:

- [x] statistics-service (note: has been moved into keptn core; version in repo might not be compatible)
  - [ ] Update Service to use CloudEvents 1.0: https://github.com/keptn-sandbox/statistics-service/issues/7
- [ ] litmus-service
- [ ] ansibletower-service
- [ ] generic-executor-service
- [ ] slackbot-service

**Definition of Done:** 
- [ ] The services in keptn-sandbox run on v0.8

### Testing framework
- Build a simple testing framework to validate that a Keptn-service sends: started/finished events
