### ISSUE TITLE
Makefile: Add command to install and run k3s

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2508]
When developing Keptn locally, it’s helpful if we could spin up a k3s server quickly, install Keptn control-plane on it, and from then on we start developing our microservices for control-plane.

## Big picture

Eventually the workflow for the developer should feel like this:
```
git clone
make run-k3s
make build-cli
bin/keptn install
cd your-microservice-directory (e.g., configuration-service)
Make your changes to the microservice
skaffold run --tail # or docker build ... and then kubectl apply ...
Test your microservice using keptn cli (e.g., keptn send-event start-evaluation ...)
Commit your changes, create a PR, etc…
[Optional; keptn uninstall]
make stop-k3s
```

Long term we also want to use this to enable developers to run integration tests locally.

## Tasks 

For this issue it is necessary to extend the makefile with the following targets/commands:

```
make install-k3s (abort if k3s is already installed)
make run-k3s (depends on install-k3s; abort if k3s is already running)
make stop-k3s (stop k3s is running)
```

See https://github.com/keptn/keptn#usage as well as https://github.com/keptn/keptn/blob/458ef9a828d5e3d34dc33ca5e76ca84bf999fcf5/.travis.yml#L593-L623 as a reference

Related to https://github.com/keptn/keptn/issues/2454 

 ## Definition of Done

- [ ] New makefile targets install-k3s, run-k3s, stop-k3s that work as described above
  - [ ] On Linux
  - [ ] On MacOS
  - [ ] [Optional: On Windows?]
- [ ] Update CONTRIBUTING.md to include the process of using make to install and run k3s

**Note**: If you can not do it on all platforms, please say so.
