### ISSUE TITLE
Auto-Deploy/Upgrade master branch to a Cloud instance

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2550]
**This story is still not 100% finished**

**To be discussed**

* Should meta-keptn just be a control-plane cluster?
* Should the deployed keptn-dev/keptn-hardening clusters deploy podtato-head or sockshop or something else? 
* Can meta-keptn update itself (e.g., as a production stage)
* Can meta-keptn also update another existing Keptn instance (e.g., public demo cluster, internal demo cluster)

---

Based on a schedule (e.g., once a day) we trigger a deployment of the current master branch to Meta-Keptn on GKE.

This means we always have an up2date environment that shows that the current master branch is working (or not).
However, right now this is one huge Kubernetes cluster, that holds multiple stages.

# Tasks

- [ ] Create two additional multi-node (2-3 nodes à 4 VCPUs) clusters on GKE and name them `keptn-meta-dev` and `keptn-meta-hardening`. Keptn Installation Type: continous-delivery + istio
- [ ] Make sure those two clusters are also monitored using the same Dynatrace Environment
- [ ] Setup nginx ingress + cert manager with lets encrypt with the hostnames `keptn-dev.*` and `keptn-hardening.*`
- [ ] Install the remote execution plane helm-service and jmeter-service on those two clusters (see https://keptn.sh/docs/0.8.x/operate/multi_cluster/ for details) and connect it to Meta Keptn instance. Limit the distributors to the project `keptn` and the respective stage `dev`/`hardening`
- [ ] On meta keptn, uninstall helm-service and jmeter-service (re-install with continuous-delivery set to false)
- [ ] On meta keptn, delete namespaces `keptn-dev`, `keptn-hardening`, `keptn-production`, `keptn-production-remote`
- [ ] Scale down meta keptn to use less nodes, but still be highly available

**Note**: The stages `production` and `production-remote` will be defined in a follow-up story.

# Acceptance Criteria

- [ ] Meta Keptn is slimmed down to a control-plane only installation
- [ ] Two additional clusters keptn-meta-dev and keptn-meta-hardening are available and can the Keptn installations on there can be reached via
