### ISSUE TITLE
Adapt CLI commands “create service”, “onboard service” and “delete service” to use endpoint of the shipyard-controller

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2557]
The shipyard-controller provides REST endpoints for creating and deleting services. 

**Tasks:**
- [x] Use these endpoints for the Keptn CLI commands: `create service`, `onboard service`, and `delete service`
- [x] Remove the flag “deployment-strategy” from the command “onboard service” because it is not needed anymore (in case a Keptn project contains Keptn services which require different deployment strategies, the user should define two different delivery sequences)
- [x] Update integration tests to use the new CLI and REST API features

**Comment by christian-kreuzberger-dtx** [comment]
CLI has already been adapted in #2266
