### ISSUE TITLE
Remove Websocket communication between CLI and API

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#2727]
The WebSocket communication is/was used for providing information to the user.
Keptn 0.8.0 now provides CRUD operations for projects and services and their responses already contain the status/result.
Hence, here no WebSocket communication is needed anymore.

The WebSocket communication is now only used in two CLI commands and we should also remove the WebSocket communication here:
- `keptn send event new-artifact`: We introduced a `sh.keptn.event.deployment.finished` event, which contains the status of the deployment. A user can query this event.
- `keptn configure monitoring`: Here I would propose to introduce a `sh.keptn.event.monitoring.configure.finished` event for reporting the result of the configuration. A user can then also query this event.

Implementing this issue would help/resolve the following issues:
- https://github.com/keptn/keptn/issues/2296
- https://github.com/keptn/keptn/issues/1929
- https://github.com/keptn/keptn/issues/1554

**Tasks:**
- [x] Remove the WebSocket communication from the CLI, i.e. commands `keptn send event new-artifact` and `keptn configure monitoring`. Furthermore, remove the flag `--suppress-websocket`
- [x] The `keptn configure monitoring` command should wait for the `sh.keptn.event.monitoring.configure.finished` event and output the result
- [x] Remove the WebSocket communication from the `api-service`
- [x] Remove the WebSocket communication from the `helm-service`
- [x] Introduce a `sh.keptn.event.monitoring.configure.finished` event in the spec and send such an event after the monitoring configuration was completed.
- [x] go-utils: Remove dead code (i.e. `websocketutil.go` and `combinded_logger.go`). Furthermore, remove `github.com/gorilla/websocket` from the dependencies
- [ ] Close the above-mentioned issues since they are obsolete then
