### ISSUE TITLE
List services in alphabetical order

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2754]
When having a long list of services, it is quite difficult to find one since they are ordered based on their creation date and not alphabetically. 

Due to pagination that is built in the API used by the Bridge, it does not make sense to sort the services on the client-side (each page would be sorted, but not the entire list of, e.g., services). Consequently, this issue should implement the sorting on the API. 

**Task:**
- [x] Implement an alphabetical sorting on each GET endpoint (`/project`, `/service`, `/stage`) of the Keptn API

**Definition of Done:**
Finally, the following screens should display the services alphabetically:
- [ ] Order services alphabetically in services screen. 
- [ ] Order services in environment screen alphabetically in tile [1] and in the right panel [2]
- [ ] Order projects in project overview (first page)

![image](https://user-images.githubusercontent.com/729071/101024797-e6d30680-3574-11eb-9d66-72cc93fee419.png)

![image](https://user-images.githubusercontent.com/729071/101024971-2994de80-3575-11eb-9182-9273d1c9899f.png)

![image](https://user-images.githubusercontent.com/729071/101629017-f9d85180-3a20-11eb-82ef-42a0002eba79.png)

**Comment by Kirdock** [comment]
This can't be done on the frontend because we have pages for services and projects. Each page can be sorted, but not the overall outcome of projects/services.
For example: Service "A-Service" is the 51th service in the list, but is going to stay on page 2 if the order isn't adjusted on the backend.

**Comment by warber** [comment]
@Kirdock @ermin-muratovic the sorting is now done in the backend. (see #2981). Docker image `keptn/configuration-service:0.8.2-dev-PR-2981` can already be used for testing. There is **no** new parameter to set in the API call. It is just alphabetically sorted per default.

**Comment by christian-kreuzberger-dtx** [comment]
The PR has already been merged, is this issue done?
