### ISSUE TITLE
Quering (root) events via mongodb-datastore is slow when there is many events in the db

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2759]
In order to troubleshoot https://github.com/keptn/keptn/issues/2744 I have spammed my Keptn 0.7.3 with a lot of cloud-events:

1. start-evaluation cloud-events in project ck-keptn-qg (probably around 200 start-evaluation root events per service for 12 services = 2400 root events)
1. new-artifact cloud-events in project ck-sockshop (probably around 80 configuration-change root events, one service)

See https://pastebin.com/qVqSZFH9 for output of statistics-service.

This allowed me to discover a performance problem and even failed API Calls in mongodb-datastore, which will affect Keptn Bridge (and probably also in other parts of Keptn, but they are not too visible to the end-user at this point).

![image (5)](https://user-images.githubusercontent.com/56065213/101135838-aaeb8000-360c-11eb-9de7-1457d3d40ebf.png)

Example for really slow calls (Response time > 10 seconds):  **<- this is where we need to improve heavily**
```
/event?root=true&pageSize=20&project=ck-keptn-qg&service=dynatrace-sli-service&fromTime=2020-12-04T07:21:15.000Z
/event?root=true&pageSize=20&project=ck-sockshop&service=carts-db
```

Examples for slower calls (around 1 second, but usually less):
```
/event?type=sh.keptn.events.tests-finished&project=ck-keptn-qg&stage=hardening&service=eventbroker-go&keptnContext=1c86c128-1703-400e-b5bb-9b2ae25d7efc&pageSize=1
/event/type/sh.keptn.events.evaluation-done?source=lighthouse-service&limit=1&excludeInvalidated=true&filter=data.project:ck-keptn-qg%20AND%20data.stage:hardening%20AND%20data.service:configuration-service%20AND%20data.result:pass
```

**Tasks:**
- [ ] Provide a script that allows to setup the environment (e.g., 20 projects, with 15 services each, + 100 evaluations) 
- [ ] Using a monitoring tool (Dynatrace or Prometheus), monitor the response time of the above-mentioned endpoints (+ note down the results) - please use this step to verify the claim that those endpoints are slow
- [ ] Create a (JMeter) Test that spams start-evaluation cloud-events; Use GET requests to query the above-mentioned endpoints
- [ ] Activate the MongoDB profiler to get more insights: https://docs.mongodb.com/manual/tutorial/manage-the-database-profiler/
- Identify the bottleneck that is causing a long response time. 

**Definition of Done**
- [ ] Update of Readme.md to list all collections used by the mongodb-datastore.
- [ ] **Document the results in the Pull Request**

--- 
**Out of scope:**
- Improve the above-mentioned endpoints (especially the root events one), either by adding indexes in MongoDB or by using other query methods
- Run the same JMeter Test again and verify that the results are better now
- Extend the endpoint to allow a list of services as a parameter when querying events. 
- Add an index for project, service, type.
