### ISSUE TITLE
Helm-service and jmeter-service do not support https and x-token based communication with configuration endpoint

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2841]
When running the helm-service and jmeter-service on the execution plane, they cannot communicate with the control-plane that exposes the configuration endpoint on `https` . The reason is that the used handlers - like ProjectHandler - have a fallback to `http`.  https://github.com/keptn/keptn/blob/04ba0b4b0bc41ea20ea4a4d5c9b88d17cf4f0cef/helm-service/main.go#L136

**As discussed**
The `distributor` should become the central component for communicating with the control-plane due to the fact that then just the distributor needs to know the access token. 

**Task**
- [ ] Enhance the distributor to communicate with the control plane via https:// and an x-token
- [ ] Distributor: Intercept calls to the configuration-service
- [ ] jmeter-service used `CONFIGURATION_SERVICE_URL` in code, but in Helm chart `CONFIGURATION_SERVICE` is defined --> change it to CONFIGURATION_SERVICE in code; https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml#L275
- [ ] In distributor support the possibility to skip TLS certificate validation: 
```
func main() {
    tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }
    client := &http.Client{Transport: tr}
    _, err := client.Get("https://golang.org/")
    if err != nil {
        fmt.Println(err)
    }
}
```

**Definition of Done:**
- Services in the execution plane can communicate with the control-plane (configuration API) via https and x-token

**Comment by johannes-b** [comment]
Please check the environment variables as mentioned here: https://github.com/keptn/keptn/issues/2646
