### ISSUE TITLE
Change `triggers` to `on` in Shipyard

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2992]
Since the term `triggers` is misleading, we agreed on changing it from `triggers` to `on`, see example: 

```
spec:
  stages:
  - name: hardening
    sequences:
    - name: artifact-delivery
      on:  
      - dev.artifact-delivery.finished
      tasks:
      - name: deployment
      - name: test
      - name: evaluation
```

**Tasks:**
- [ ] Update the enhancement proposal: https://github.com/keptn/enhancement-proposals/pull/6 
- [x] Update the keptn/spec for the Shipyard and change `triggers` to `on`: https://github.com/keptn/spec/blob/master/shipyard.md  
- [x] Adapt the struct for the shipyard in the go-utils: https://github.com/keptn/go-utils/blob/master/pkg/lib/v0_2_0/shipyard.go#L32
- [x]  Shipyard-controller
- [x]  `keptn upgrade project` that converts an old Shipyard to the new one + documentation on: https://keptn.sh/docs/0.8.x/operate/upgrade/
- [ ]  Update the `keptn/examples` and `keptn/tutorials` accordingly
- [x]  Test assets for integration tests

**Definition of Done:**
- [ ] The term `triggers` in Shipyard v0.2 is replaced by `on` and *surrounding* artifacts (i.e., the proposal, spec, examples, tutorials) are updated.

**Comment by johannes-b** [comment]
Please consider updating the files touched by: https://github.com/keptn/keptn.github.io/issues/661

**Comment by warber** [comment]
some additional aspects which came up during implementation:
1) turned out that `on` is a pretty bad choice. In yaml 1.1 specification `ON | on | OFF | off` were considered to be interpreted as boolean values. In yaml spec 1.2 the scalars `on` and `off` are shall be interpreted as strings. Indeed the `go-yaml` implementation is treating these keywords specifically by quoting them which results in:

```
...
- name: "rollback"
   "on":  << ---------------
  - staging.artifact-delivery.finished:
    selector:
      match:
        result: failed
...
```
2) A yaml **sequence** for triggers as proposed in this ticket cannot be used because we are dealing with dynamic names for triggers stated as keys. Thus, the child element of `on` needs to be a `map/dict` instead of a sequence.

Looking at these two issues, my proposal would be:

```
spec:
  stages:
  - name: staging
    sequences:
    - name: rollback
      triggered-on:
        staging.artifact-delvivery.finished:
          selector:
            match:
              result: failed
      tasks:
        - name: deployment
        - name: test
        - name: evaluation
```

**Comment by warber** [comment]
@agrimmer @bacherfl  @johannes-b

 Agreed on `triggeredOn` as name for triggers.

 Further, to support triggers **without selectors** in a clean way we'll use the following structure:

```
spec:
  stages:
  - name: staging
    sequences:
    - name: rollback
      triggeredOn:
         - event: "staging.artifact-delivery.finished"
           selector:
             match:
                result: failed
      tasks:
        - name: deployment
        - name: test
        - name: evaluation
```

where `selector` is optional.
