### ISSUE TITLE
Reduce K8s resource limits/requests to what is actually necessary

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3018]
I feel that our resource requests and limits as we have defined them in our helm charts could be improved on:

| Pod | Container | lim.cpu | lim.mem | req.cpu | req.mem | Images |
|-----|-----------|---------|---------|---------|---------|--------|
| api-gateway-nginx | api-gateway-nginx | 500m | 128Mi | 50m | 32Mi | docker.io/nginxinc/nginx-unprivileged:1.19.4-alpine | 
| api-service | api-service | 500m | 256Mi | 50m | 64Mi | docker.io/keptn/api:0.8.3-dev-PR-3010 | 
| api-service | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| bridge | bridge | 500m | 128Mi | 50m | 64Mi | docker.io/keptn/bridge2:0.8.3-dev-PR-3010 | 
| configuration-service | configuration-service | 500m | 128Mi | 50m | 64Mi | docker.io/keptn/configuration-service:0.8.3-dev-PR-3010 | 
| configuration-service | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| gatekeeper-service | gatekeeper-service | 500m | 128Mi | 50m | 32Mi | docker.io/keptn/gatekeeper-service:0.8.3-dev-PR-3010 | 
| gatekeeper-service | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| helm-service | helm-service | 1 | 512Mi | 50m | 128Mi | docker.io/keptn/helm-service:0.8.3-dev-PR-3010 | 
| helm-service | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| jmeter-service | jmeter-service | - | - | 50m | 64Mi | docker.io/keptn/jmeter-service:0.8.3-dev-PR-3010 | 
| jmeter-service | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| lighthouse-service | lighthouse-service | 500m | 1Gi | 50m | 128Mi | docker.io/keptn/lighthouse-service:0.8.3-dev-PR-3010 | 
| lighthouse-service | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| mongodb | mongodb | 100m | 300Mi | 50m | 64Mi | docker.io/centos/mongodb-36-centos7:1 | 
| mongodb-datastore | mongodb-datastore | 500m | 128Mi | 50m | 32Mi | docker.io/keptn/mongodb-datastore:0.8.3-dev-PR-3010 | 
| mongodb-datastore | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| remediation-service | remediation-service | 500m | 1Gi | 50m | 64Mi | docker.io/keptn/remediation-service:0.8.3-dev-PR-3010 | 
| remediation-service | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 
| shipyard-controller | shipyard-controller | 500m | 128Mi | 50m | 32Mi | docker.io/keptn/shipyard-controller:0.8.3-dev-PR-3010 | 
| shipyard-controller | distributor | 250m | 32Mi | 25m | 16Mi | docker.io/keptn/distributor:0.8.3-dev-PR-3010 | 

E.g., why do certain services have so high requested memory settings?
Why does jmeter-service not have a a limit?
Why does helm-service have such a high memory request and limit?

# Tasks

- [ ] Check actual memory usage of all containers (except distributor) 
- [ ] Reduce memory requests according to what the container (except distributor) usually needs
- [ ] Set memory limits to what the container uses during heavy load (might only be relevant for JMeter and Helm)
- [ ] Set CPU requests to something reasonably low (e.g., 25m or 50m) for all containers (except distributor) 
- [ ] Set CPU limits to something reasonably low (e.g., 250m or 500m), depending on what kind of CPU we expect on the container (e.g., `lighthouse-service` does some calculation and might need a higher limit than `gatekeeper-service`)
- [x] Ask @agrimmer about usage data on testing environment of keptn

# Definition of Done

- [ ] All CPU and Memory requests/limits (except distributors) checked and/or adapted reasonably
- [ ] Setup verified by testing our examples (onboarding + jmeter): no container runs into memory or cpu problems
- [ ] All containers have a cpu and memory limit

**Comment by christian-kreuzberger-dtx** [comment]
Here is a screenshot of MAX memory usage of my Keptn 0.8.0 installation in the last 24 hours:
![image](https://user-images.githubusercontent.com/56065213/110750897-7b6b9580-8243-11eb-8572-0013804988b3.png)

**Comment by johannes-b** [comment]
When we have the `master Keptn` running for the Keptn deliver Keptn use-case (#3554) and set up monitoring (#3556) the basis for deriving another set of usage data is available. The missing point is then the daily (or commit-based) delivery of Keptn as tackled by #2797. 

Afterwards, we can derive monitoring data from the core components of the `master Keptn` to have a second set of reference data.

- [ ] I would also like to derive an answer to the question: *How much disk space requires MongoDB for x events?*

**Comment by mowies** [comment]
Is there a specific reason why the distributor resource requests/limits should not be touched in this issue?
