### ISSUE TITLE
Extract the rollback task of the helm-service and subscribe to sh.keptn.event.rollback.triggered

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3029]
The task of performing a rollback has to be implemented as separate tasks and not be combined with the release task.

**Tasks:**
* [x] Define a struct in the go-utils for rollback task
* [x] Move the implementation of the rollback into a dedicated event handler in the helm-service
* [x] Change the distributor of the helm-service in the installer (+ /deploy/service.yaml) to subscribe to: `sh.keptn.event.rollback.triggered`
* [x] Add the reserved keyword `rollback` to spec: https://github.com/keptn/spec/blob/master/shipyard.md#reserved-keptn-tasks
* [x] Update of the shipyard upgrader functionality since the rollback is now modeled as separate sequence
* [ ] Update of keptn/examples to add this additional rollback sequence

**Definition of done:**
* [ ] ~~Use the new send event of go-utils~~
* [x] I can subscribe/unsubscribe the helm-service from `rollback.triggered`

**Comment by warber** [comment]
Should we name the task to something like `rollbackdeployment` instead of `rollback` ?

**Comment by christian-kreuzberger-dtx** [comment]
As Keptn is very biased towards continuous-delivery and operations, I believe the term `rollback` is okay (same as for release).
