### ISSUE TITLE
Keptn CLI Command to generate service/integration based on keptn-sandbox/keptn-service-template-go

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3034]
**Tasks**

Depending on the keptn cli version, download and use the template from https://github.com/keptn-sandbox/keptn-service-template-go (by matching the Keptn CLI version with a GitHub release of the template; as a fallback: use master branch) and requests the following inputs from the user:

* Service name
* Docker Image Name (organization/image-name)
* comma separated list of cloud-events to listen for (e.g., sh.keptn.event.deployment.triggered)
* TBD

Keptn CLI then creates a directory service-name with the appropriate contents of the template, and replaces the occurrences of several strings according to the README file of the template (using go-templates).

**Definition of Done**

- [ ] Task from above is implemented in the CLI
- [ ] Keptn service template is an actual template with placeholders
- [ ] Keptn service template contains a docker-compose file to run the service locally (distributor + service) 
- [ ] Keptn service template is generated using the CLI command keptn generate keptn-service <service-name> [--keptn-service-template-version=master]
- [ ] Integration Test is added to keptn/keptn: Use the implemented CLI command with the master branch of the keptn-service-template and it should at least do the following:
   - go test ...
   - docker build …
   - docker run … 
   - Run the service and send a cloud-event (e.g., one from the test-events directory of the template) to the service; service should respond with status code 200
   - Update documentation at https://keptn.sh/docs/0.8.x/integrations/custom_integration/ (see keptn/keptn.github.io repo) to include the new command for generating a keptn-service

**Comment by jetzlstorfer** [comment]
I'll take this for LFX mentorship program.

**Comment by rahul799** [comment]
Hey @jetzlstorfer, I will like to take this issue up for LFX mentorship.
Should I start drafting a proposal for the same?

**Comment by jetzlstorfer** [comment]
Hi @rahul799 - this is issue is reserved for the LFX mentorship. We will start assigning it once the application period closes and the mentors have made their decision for the mentorship. If you would like to apply, please do so via the LFX mentorship program and add your proposal to the application! Thank you!

**Comment by rahul799** [comment]
Yeah sure. Thankyou @jetzlstorfer.

**Comment by DarthBenro008** [comment]
Hey @jetzlstorfer !

I have been selected as a mentee for this project under [LFX Mentorship Program](https://mentorship.lfx.linuxfoundation.org/project/630a656a-74ee-4494-9467-b10201ae9b20), would like to get started on this issue!
