### ISSUE TITLE
Update go-openapi libraries to latest version

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3196]
dependabot is going crazy for go-openapi libraries and is creating many PRs, e.g.:

* https://github.com/keptn/keptn/pull/3191
* https://github.com/keptn/keptn/pull/3190
* https://github.com/keptn/keptn/pull/3188

Affected modules:
* go-openapi/swag
* go-openapi/errors
* go-openapi/loads
* go-openapi/validate
* go-openapi/spec

Some of them are unfortunately incompatible.

# Tasks

- [ ] Figure out what the version/releasing model of go-openapi is (e.g., why is there a 0.20.x for some, but only a 0.19.y for some others)
- [ ] Describe the version/releasing model in the PR
- [ ] Update the respective modules and fix incompatible code in [keptn/go-utils](https://github.com/keptn/go-utils)
- [ ] Update the respective modules and fix incompatible code in [keptn/go-utils](https://github.com/keptn/kubernetes-utils)
- [ ] Update go-utils, kubernetes-utils and the respective modules and fix incompatible code in [keptn/keptn](https://github.com/keptn/keptn)
