### ISSUE TITLE
Delete helm-service and jmeter-service from continuous-delivery Helm Chart and adapt CLI accordingly

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3350]
With #3253 the helm-service and jmeter-service provide their individual Helm Chart. Consequently, there is no need to maintain them in the continuous-delivery Helm Chart here: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml

**Task**
- Remove the helm-service and jmeter-service from the continuous-delivery Helm Chart
- Adapt the CLI to install the Helm Charts for helm-service and jmeter-service when executing  `keptn install --use-case=continuous-delivery` -> add a separate `helm install` for both charts. 
- Verify building Helm Charts in CI works

**Definition of Done:**
- [ ] When executing `keptn upgrade` from 0.8.0 to 0.8.x the upgrade has to work
- [ ] When executing `keptn install --use-case=continuous-delivery` the control-plane including the helm-service and jmeter-service are installed on my cluster. (No changed behaviour for the end-user) 
- [ ] `keptn install --chart-repo=...` still works so we can install builds directly from GitHub

**Comment by christian-kreuzberger-dtx** [comment]
FYI, this should be as simple as doing this in the CLI:
```
helm install jmeter-service https://github.com/keptn/keptn/releases/download/0.8.0/jmeter-service-0.8.0.tgz -n keptn
helm install helm-service https://github.com/keptn/keptn/releases/download/0.8.0/helm-service-0.8.0.tgz -n keptn
```

At the moment we are also supplying jmeter and helm-service charts at google cloud, so it might even work using the same chart repo.
