### ISSUE TITLE
Fix deprecated api types for Kubernetes 1.22

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3444]
When installing Keptn 0.8.0, the following warning is displayed:

```
W0305 07:33:46.510515   16254 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
```

Additionally, with Keptn 0.9.2, the following warning is displayed in the CLI:
```
extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

# Tasks

- [ ] Use a tool to automatically check for deprecated types/apis in Kubernetes manifests / Helm Charts
- [ ] Fix deprecations (e.g., the above ones) in Keptn core (CLI, api-service, shipyard-controller, ...)
- [ ] Notify keptn-contrib and keptn-sandbox repos about this by creating issues with necessary changes in Kubernetes manifests / Helm Charts

**Comment by adigeak** [comment]
@johannes-b can you assign this to me?

**Comment by adigeak** [comment]
Hi @christian-kreuzberger-dtx 
I'm trying to recreate the problem using 
`curl -sL https://get.keptn.sh | KEPTN_VERSION=0.8.0`
i can not see the problem.
Is this the right way?

**Comment by mowies** [comment]
Hi @adigeak 
Sorry for the super late reply. Still wanna work on this issue? I can support you in this.
