### ISSUE TITLE
Setup master Keptn and execution plane 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3554]
*Remark:* This issue requires some manual tasks, which must be scripted to have an automation script to easily reproduce these steps.

Supporting material: https://drive.google.com/file/d/1MOovypqjO-7tmhkYWpsI-yPgAXzsk-Ac/view?usp=sharing

**Steps:**
- Setup a GKE cluster for: 
    - keptn-control-plane: which size is required - https://keptn.sh/docs/0.8.x/operate/k8s_support/#cluster-size
    - keptn-remote-plane: (set on Autopilot?)
- *on keptn-control-plane* 
  - `keptn install --use-case=continuous-delivery` to install "master Keptn" 0.8.x (based on latest stable release)
 - *on keptn-remote-plane* 
  - Install helm-service using: `helm install helm-service` and connect it to keptn-control-plane (download Chart from GitHub release)
  - `helm test helm-service` has to pass
  
**Setup Keptn project/service:**
- `keptn create project [tanus]` with a shipyard derived for the example as shown here: https://drive.google.com/file/d/1MOovypqjO-7tmhkYWpsI-yPgAXzsk-Ac/view?usp=sharing 
- `keptn create service(s)`: keptn, dynatrace-service, dynatrace-sli-service
- `keptn add-resource` (Helm Charts of Keptn 0.8.1, dynatrace-sli-service, dynatrace-service): download Charts from GitHub releases

**Tasks:**
- Provide a script that allows to create a GKE cluster and install Keptn
- After a successful installation, setup Keptn project/services using script 
- Bundle the install + setup into a GH action. 

Follow up issue: **Ship a Keptn “self-monitoring” project** #3556 

**Definition of Done**
- [ ] The above listed steps are scripted/automated allowing to reproduce the setup by just executing a GitHub Action. 
- [ ] keptn trigger delivery --service=keptn → deploys Keptn 0.8.x on all stages (assuming someone clicked the approval button for production stage) 
- [ ] keptn trigger delivery --service=dynatrace-service/dynatrace-sli-service → deploys the services to all stages.

**Comment by christian-kreuzberger-dtx** [comment]
Quick comment regarding this sub-task:
* Bundle the install + setup into a GH action.

I wonder if it makes sense to bundle the cluster creation/setup + Keptn Install into a single GH action.

As a developer I can see the benefit of having an action which prepares the cluster, and another action that installs Keptn.

This also provides the benefit of being able to switch the cluster creation to a different cloud provider (or use K3s locally)
