### ISSUE TITLE
Ship a Keptn "self-monitoring" project

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3556]
Follow up of: #3554 

*Remark:* This issue requires some manual tasks, which must be scripted to have an automation script to easily reproduce these steps.

*Supporting material:* Provide an option to automatically install Keptn “self-monitoring” using Dynatrace, e.g. https://github.com/christian-kreuzberger-dtx/ck-keptn-qg/tree/master 

This needs:
- Proper SLOs and SLIs for each microservice
- Create a Dynatrace SaaS tenant (or re-use the tenant from the demo cluster)

On the `master Keptn`, which is running on the `keptn-control-plane`:
- Deploy Dynatrace OneAgent on the cluster running the `master Keptn`
- Add dynatrace-sli-service and dynatrace-service to the master Keptn
- Configure lighthouse service to use dynatrace-sli-service for the [tanus] project
- Provide connection to the Dynatrace tenant by adding the `dynatrace` secret (using the Keptn /secret API)
- Add SLO/SLI values for the `keptn` service in the hardening stage (this config will be used by the test #2549)

**Supporting material:**
- https://github.com/bacherfl/keptn-dt-monitoring

**Task:**
- Implement a GH action (keptn-contrib) that automates the above steps. 

**Definition of Done**
- [ ] The above listed steps are scripted allowing to reproduce the setup by just executing a GitHub Action that lives in github.com/keptn-contrib
- [ ] The master Keptn is monitored using Dynatrace
- [ ] keptn trigger delivery --service=keptn → now the deployments are monitored and an SLO evaluation is conducted in the hardening stage
