### ISSUE TITLE
Deployment.finished events: Establish mapping between stage and deploymentURIs

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#3564]
Currently, the fields `deploymentURIsLocal` and `deploymentURIsPublic` are implemented as a simple array. This leads to problems in the following scenario:

```
      "deploymentURIsLocal": [
        "http://simplenode.demo-delivery-dev:80",
        "http://simplenode.demo-delivery-staging:80"
      ],
      "deploymentURIsPublic": [
        "http://simplenode.demo-delivery-dev.*****",
        "http://simplenode.demo-delivery-staging.****"
      ],
```      

These arrays contain deploymentURIs from different stages - therefore, a service that needs those URIs, e.g., the `jmeter` service will not be able to tell which URI should be used for executing tests in a certain stage.

A solution for that would be to introduce a mapping between the stage and the URIs, e.g.:

```
      "deploymentURIsLocal": {
          "dev": ["http://simplenode.demo-delivery-dev:80"],
          "staging": ["http://simplenode.demo-delivery-staging:80"]
      }
```

**Tasks:**

- [ ] Update the [spec](https://github.com/keptn/spec) to reflect those changes in the `deplyoment.finished` event
- [ ] Update the [go-utils](https://github.com/keptn/go-utils) to reflect those changes in the `deplyoment.finished` event
- [ ] Update the jmeter-service to handle the new format of the `deploymentURIs` properties
- [ ] Update the bridge to handle the new format of the `deploymentURIs` properties
