### ISSUE TITLE
Research: Service screen revamped to improve UX

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3630]
To get a great UX on the service screen, the current mockup (see below) has to be refined with the following main questions in mind: 

* [x] As a user, I would like to see the deployments of a service that are currently deployed in my stages.
* The main use-cases, which are continuous delivery, quality gate, and auto-remediation, are present and drive the usage of this screen.
  * [x] Can I get the deployment URLs?
  * [x] What is the quality gate (evaluation) result of deployment `xyz` in stage `abc`? 
  * [ ] Can I see which remediation happened on a deployment?
* [x] I would like to see all labels for a particular deployment since they provide context information and supporting links.
* [x] I would like to see the `SLO.yaml` / `remediation.yaml` configured for a service (deployment of a service).
* (more relevant questions may arise when working on the mockup)

**Task:**
- Use the mockup (wireframe) - as implemented in a pptx - to design the service screen.
- If the mockup is solid, derive components that can be implemented independently

**Definition of Done:**
- [x] The mockup(s) provide a good understanding of the look-and-feel of this screen.
- [ ] Concrete components are derived and broken down into sub-issues.

**Mockup**

![image](https://user-images.githubusercontent.com/729071/112599452-3c773b80-8e10-11eb-8b3d-11e9028cfd14.png)

**Comment by johannes-b** [comment]
The current status of this issue is documented here: https://github.com/keptn/enhancement-proposals/issues/40
