### ISSUE TITLE
Keptn API: GET `/project/{project}` returns 200 instead of 404

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3699]
When using the GET `/project/{project}` endpoint with a not-existing `project`, the API returns a 200 with `null` in the body. 

**Expected behavior:** 
- Like the `/project/{project}/stage/{stage}/service/{service}` endpoint ...
- return a **404** with the body: 
```
{
  "code": 404,
  "message": "project not found"
}
```

**Tasks:**
- Adapt the endpoint
- Make sure the Bridge uses the new endpoint implementation
- Check integration tests and swagger-UI

**Definition of Done:**
- [ ] Integration tests working, swagger-ui correctly updated
- [x] The GET `/project/{project}` API returns a 404 when the project is not found
- [x] Bridge is working correctly; Proper error handling for 404 error in Bridge

**Comment by warber** [comment]
Changes in API are done 
@laneli will take care of the necessary changes in the bridge

**Comment by laneli** [comment]
In the bridge get project is not used - so the issue is only related to the API.
Nonetheless the unused getProject code was removed from the code.
