### ISSUE TITLE
Filter for Service(s) in Environment Screen

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3759]
**User story:** As a user, I would like to see the deployments of a service that are currently running in the environment (i.e., the different stages)

The environment screen provides this information, but this is difficult to grasp when many services are managed in this project. 

**Improvement:** Add a filter component to the environment screen that allows filtering for *Services*: 
* Filter allows multi-selection:
![image](https://user-images.githubusercontent.com/729071/114374215-b08d3f80-9b83-11eb-94c9-6cddd855f58e.png)
* Filter is added on top: 
![image](https://user-images.githubusercontent.com/729071/113976105-d2638b00-9840-11eb-8342-c2d6f858a879.png)

**Task:**
- Persist the filter (Implementation details: either as a cookie or in the local storage?) to have the filter pre-selected when reloading the page.
- Update the documentation on keptn.sh: (1) Update of screens + (2) Behaviour of storing data. 

**Definition of Done:**
* [ ] Depending on the service(s) selected by the filter, the view is reduced to the list of services. This includes: 
  - [ ] Information in the stage tiles
    - List of services 
    - Status of the stage (icons need to reflect the current status under consideration of the filter)
  - [ ] Details in the right component
* [ ] Filter stays active when switching pages or reloading

**Comment by srisatya1197** [comment]
Is anyone working on this isssue?

**Comment by johannes-b** [comment]
No, it has not been assigned to someone yet. Would you like to work on it? :) 

For your interest, the Bridge already uses this filter component at another place: 
![image](https://user-images.githubusercontent.com/729071/114592743-8cb52100-9c8b-11eb-9ad4-32df31b7f5d4.png)

**Comment by srisatya1197** [comment]
Ok Sir.

**Comment by srisatya1197** [comment]
I anticipated it was assigned ,

**Comment by johannes-b** [comment]
@srisatya1197 it was not assigned to anybody, but I assigned it to you. Are you okay with that?

**Comment by srisatya1197** [comment]
Totally Sir. If I have any doubts where should I clarify them Sir?

**Comment by srisatya1197** [comment]
Totally ok Sir. Sir if I had any trouble while forking or any other should I ask here or in slack channel?
