### ISSUE TITLE
Meta Keptn: Use the new endpoints.yaml for deployment URI

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4180]
With Keptn 0.8.3 we have a new way of defining endpoints/URIs for deployments using the user-managed strategy.

Right now the deployment is triggered using the following code:
https://github.com/keptn/keptn/blob/0f24233122a216b6bf597731f8673f345b841e0c/.github/workflows/integration_tests.yml#L990-L996

This should be changed using the new endpoints.yaml, as described here: https://keptn.sh/docs/0.8.x/continuous_delivery/deployment_helm/#user-managed-deployments-experimental

Within this task, also provide an ingress manifest for each stage of "Keptn on Keptn".

# Acceptance Criteria

- [x] Deployment of Keptn with Keptn uses `endpoints.yaml` 
- [x] Each stage of "Keptn on Keptn" has a unique URI
- [x] Each stage of "Keptn on Keptn" can be reached via HTTPS
