### ISSUE TITLE
Research: Zero Downtime Upgrade/Downgrade of Keptn

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4182]
This is a research issue to figure out the steps required such that the following user story holds:

**User Story**

As a user, I want to be able to upgrade (or downgrade) my Keptn installation without losing access to the API and without losing CloudEvents / Tasks / Sequences (both, currently running sequences/tasks as well as new sequences/tasks).

**Examples/Use-Cases**

* While upgrading the Keptn installation, a user triggers an evaluation
* While upgrading the Keptn installation, a user triggers a sequence with a task with `triggeredAfter: 15m` (essentially shipyard-controller needs to sleep during that time)
* While upgrading a Keptn installation, a problem is triggered by Dynatrace and Keptn needs to perform a remediation action
* While upgrading a Keptn installation, an external execution-plane service tries to access a file from configuration-service (via api-gateway-nginx)

# Tasks

- [ ] Identify which components / services / ... are restarted during an upgrade/downgrade (e.g., all? Are NATS / mongodb pods restarted?)
- [ ] Identify which components / services / ... could just use `RollingUpdate` strategy of Kubernetes to prevent downtime (e.g., `api-gateway-nginx`, `bridge`) - Note: if a service uses a persistant volume, this might not work! 
- [ ] Identify what would happen if we ever want to upgrade mongodb. Would it cause a downtime of mongodb? 
- [ ] Identify what would happen if we ever want to upgrade NATS. Would it cause a downtime of NATS?

**Comment by johannes-b** [comment]
This issue is time-boxed for two persons for 2 days.

**Comment by warber** [comment]
## Nats Streaming (STAN) Research:

### General
* STAN is a project on its own which is based on NATS
* STAN extends NATS Core with **guranteed message delivery** and **message persistance**

### Installation
* Helm chart for STAN available here: https://github.com/nats-io/k8s/tree/master/helm/charts/stan
* It is possible to use *already existing* NATS Core Server and install NATS streaming server alongside


### Acks and redelivery
* NATS core only supports *at-most-once* message delivery (you get the message at most once or never)
* STAN supports *at-least-once* message delivery (you get min. one copy of the message)
* STAN auto acks messages, Client can also use manual ACKS. If the client does not send a manuacl ACK,
the server *redelivers* the message


### Durable Subscriptions
* Subscription survives client/consumer fails
* Guarantees message delivery of a subscriber when it is stopped and started again
* As soon as a new client (with the same *client id* and *durable subcription name* is started, it
* gets all the missed messages.


### Queue Subscriptions:
* additional to a "normal" subscription we need to define a "group name" in which messages are distributed
* a message is delivered to *only one* member of the group
* subscribers needs to have unique client IDs
* useful for scaling out


### Message Archiving
* messages are stored as files /store/<channel>/
* these files (messages) can be archived using scripts
* the scripts used to archive messages needs to be a exectuable binary (e.g. written in GO)
* STAN server needs to be started using -file_slice_archive=<execuatable>


### Replication of NATS streaming:
* Replicating the cluster
  * quroum based, you need to have more than n/2 nodes available to avoid split brain
  * messages get stored to disk by the leader and forwarded to other nodes
* Fault Tolerant mode:
  * Active-Passive
  * does not need a quorum
  * does not replicate the data, hence requires a distributed FS


### Required Changes to support ZeroDowntimeUp/Downgrades / HA (WIP)

* messages shall only be acked iff they were successfully stored into the database (shipyard controller/distributor)
* use NATS Streaming API instead of NATS Core API (distributor)
* also pass a **clientID** when connecting to the broker (distributor)
* use durable subscription to subscribe to survive restart or up/downgrade (distributor)
* installation of NATS Streaming via the installer using a different helm chart OR using existing NATS Core installation and
installing NATS Streaming Server alongside
* all services must be idempotent wrt the at-least-once message delivery model of NATS Streaming


### Long term changes
NATS Streaming is able to persist events and (re)deliver them to new clients. Clients can request
receiving events from a given time in the past, an index or all available event.
Using this feature, data held by the ShipyardController shall be re-constructed using the persisted events of NATS Streaming.

**Comment by warber** [comment]
## Keptn Components which get restarted during an `keptn upgrade`

*statistics-sevice*: yes
*configuration-service*: yes
*secret-service*: yes
*shipyard-controller*: yes
*approval-service*: yes
*lighthouse-service*: yes
*mongodb-datastore*: yes
*api-service*: yes
*brdige*: yes
*remediation-service*: yes
*keptn-nats-cluster*: **no**
*mongodb*: **no**

**Comment by warber** [comment]
## Rolling Updates for services

### General
`RollingUpdate` on K8S is enabled by default. However, to avoid zero downtime the deployments need to have a `ReadinessProbe` configured. In principle, this is the case, however, some of our services do not have a *meaningful* readiness probe configured, e.g., some services just provide a separate HTTP endpoint that is not related to the actual endpoint served by the service. 

| service | readinessprobe | 
|---------|----------------|
| api-gateway-nginx         |  OK            | 
| api-service       |      NOK           |   
|  approval-sevice       |       NOK          |  
| bridge | N/A | 
| configuration-service | NOK |
| helm-service | NOK |
| jmeter-service | NOK |
| lighthouse-service | NOK | 
| mongodb | N/A |
| mongodb-datastore | NOK |
| remediation-service | NOK |
| shipyard-controller | OK |
| statistics-service | OK |
| nats | OK |

**Comment by warber** [comment]
## Rolling Update for NATS Server

<TBD>

**Comment by bacherfl** [comment]
## Rolling Update for Mongodb

Currently, we are deploying our mongodb as a k8s `Deployment` with `Recreate` strategy and 1 replica.

To guarantee zero-downtime, and also high availability, it is recommended to use a `StatefulSet` for deploying the database.

As a proof of concept, I have deployed the database with the following configuration:

```
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  selector:
    matchLabels:
      app: mongo
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        app: mongo
    spec:
      serviceAccountName: keptn-default
      securityContext:
        fsGroup: 184
      terminationGracePeriodSeconds: 10
      containers:
        - image: "docker.io/centos/mongodb-36-centos7:latest"
          name: mongo
          args:
            - run-mongod-replication
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-rs-volume
              mountPath: /var/lib/mongodb/data
          env:
            - name: MONGODB_DATABASE
              value: "keptn"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongodb-credentials
                    key: password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongodb-credentials
                    key: admin_password
            - name: MONGODB_REPLICA_NAME
              value: "mongodb-replicaset"
            - name: MONGODB_KEYFILE_VALUE
              value: "mykeyfilevalue"
            - name: MONGODB_SERVICE_NAME
              value: mongo
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/initialized
          securityContext:
            runAsNonRoot: true
            runAsUser: 184
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      name: mongo-rs-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

after applying this `StatefulSet` in the `keptn` namespace, I verified that the three replicas have been created:

```
$ kubectl get pods -n keptn -lrole=mongo
NAME      READY   STATUS    RESTARTS   AGE
mongo-0   1/1     Running   0          71m
mongo-1   1/1     Running   0          71m
mongo-2   1/1     Running   0          70m
```

Afterwards, I tried to update the database by changing the image tag: As expected the update was applied to one pod one after another, while always maintaining at least one running instance of the replica set.

In the services using the database, the connection string had to be adapted by appending the name of the replica set, e.g.:

```
mongodb://<user>:<password>@mongo:27017/keptn?replicaSet=mongodb-replicaset?replicaSet=mongodb-replicaset
```

**NOTE:** One drawback of deploying the database as a `StatefulSet` is that it is not straightforward to use `kubectl port-forward` to connect MongoDB compass to the database anymore, which has a negative impact on the developer experience. The reason for that is that when connecting to a replicaSet, the mongodb cluster returns a list of available Hostnames to connect to, e.g.:

```
mongo-0.mongo.keptn.svc.cluster.local (primary)
mongo-1.mongo.keptn.svc.cluster.local
mongo-1.mongo.keptn.svc.cluster.local
```

These URLs are then used by Mongodb Compass to connect to an instance of the replicaset, but of course these cluster-internal server names cannot be resolved on the local developer machine.
Maybe this can be addressed by using a proxy service within the cluster and connecting to that via MongoDB Compass.

Maybe another option to consider is to use the mongodb K8s operator to deploy the database. As documented here, this one seems to handle upgrades to the database more efficiently, as documented here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/architecture.md#example-mongodb-version-upgrade

**Comment by bacherfl** [comment]
Update regarding the mongodb community operator (https://github.com/mongodb/mongodb-kubernetes-operator): I just tried to deploy a mongodb replica set using the operator instead of using a plan K8s StatefulSet. The deployment was working fine, and also the connection with MongoDB Compass via port forwarding was working. However, when I tried to update the mongodb version for the ReplicaSet (as described in the [documentation](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#upgrade-your-mongodb-resource-version-and-feature-compatibility-version)) the operator was not able to handle this properly - it seemed like the update was not applied and the pods of the replica set were restarting continuously, with the version still set to the previous value. I tried this with versions 0.6.0, 0.6.2 and 0.7.0 of the mongodb operator, but the behaviour was the same in all cases

**Comment by bacherfl** [comment]
*Update regarding Configuration Service (Shared Git repo):*

If the health checks are in place, and we can apply the RollingUpdate strategy for updates to the configuration service, meaning that only one instance of the service is running at a certain point in time, we will not have the problem of multiple instances sharing the same git repository. 
If however, we do have the need of running multiple instances of that service in parallel, we need to implement a global locking mechanism to prevent concurrent write operations in the git repo. This could be done using distributed Redis locks, e.g. with the following library: https://github.com/go-redsync/redsync
