### ISSUE TITLE
Install Lets-Encrypt on Meta Keptn instance, make sure API and Bridge are only accessible via SSL

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4185]
Right now the API (and Bridge) for our Meta Keptn is accessible directly via HTTP.

We should change this such that it is only accessible via HTTPS and Lets Encrypt certificates.

# Tasks

- Come up with a cool/fitting name (e.g., pipeline.keptn.sh or integration-tests.keptn.sh) instead of 1.2.3.4.nip.io

# Definition of Done

- [x] Let's Encrypt is installed and activated on Meta Keptn for Keptn API and Bridge
- [x] Public facing host for API / Bridge is changed from an IP Address to something like xyz.keptn.sh
- [x] It is no longer possible to access API / Bridge *without* SSL (e.g., HTTP://1.2.3.4). 
- [x] [Secret META_KEPTN_API_URL](https://github.com/keptn/keptn/settings/secrets/actions) is changed accordingly

**Comment by mowies** [comment]
working on this now

**Comment by christian-kreuzberger-dtx** [comment]
We noticed that istio does not support certificates in separate namespaces (they need to be in istio-system; see https://github.com/istio/istio/issues/14598 for details). Therefore we will switch to nginx-ingress, which supports certificates per namespace.
