### ISSUE TITLE
Authenticating (1) a user on Bridge or (2) Keptn CLI on `/auth` endpoint are not throttled

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4323]
## Action Item

*Details:* A user can make limited use of the APIs: `bridge login` (to login to the Bridge using basic auth) and `/auth` (to authenticate Keptn CLI). Hence, a brute-force attack could be used to guess the password. 

**Task:**
- [x] Throttle basic auth requests in bridge-server 
- [x] Throttle requests to /auth in api-service

Throttling shall be done per IP address.

### Definition of Done
- [x] Implement Throttling of requests to avoid Brute Force attacks
