### ISSUE TITLE
Remove the /config/bridge/ endpoint

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#4589]
## Action Item
The REST endpoint GET and POST `/config/bridge/` returns the username and password used to login to the bridge. 

**Task**:

- Remove the endpoint from the backend
- Remove the CLI `-o` flag from `configure bridge`

### Definition of Done
 
- [x]  `keptn configure bridge --output` does not output any credentials, but just gives the user a hint how to get the credentials using `kubectl`
- [x] Remove the `/config/bridge/` endpoint
- [ ] Update the [documentation](https://keptn.sh/docs/0.8.x/operate/install/#authenticate-keptn-bridge) to set up a new user
- [x] Adapt integration tests (look where `keptn configure bridge --output` or the endpoint is directly used)

**Comment by agrimmer** [comment]
Please also remove the POST endpoint `/config/bridge` because this could be also done via `kubectl`.
Furthermore, `/config/bridge` is not needed if OAuth is used.
By removing the POST endpoint `/config/bridge`, we indirectly also solved https://github.com/keptn/keptn/issues/4435.

**Comment by warber** [comment]
Changes in `keptn/keptn`are done.

:exclamation: Still missing: update of the documentation and tutorials.
