### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#467]

**Comment by bacherfl** [comment]
**Release date**
29-05-2019

**This release contains**
- [ ] #380 

---
### Phase 1 - Release of external keptn services

**foreach:**
- [ ] github-service > **github-service:0.2.2.latest**
- [ ] servicenow-service > **servicenow-service:0.1.2.latest**
- [ ] dynatrace-service > **dynatrace-service:0.1.2.latest**
- [ ] pitometer-service > **pitometer-service:0.1.3.latest**
- [ ] jmeter-service > **jmeter-service:0.1.0.latest**
- [ ] helm-service > **helm-service:0.1.0.latest**
- [ ] gatekeeper-service > **gatekeeper-service:0.1.0.latest**
- [ ] openshift-route-service > **openshift-route-service:0.1.0.latest**

  **begin**

    - [ ] all feature/bugfix/hotfix branches merged into develop
    - [ ] inactive branches deleted
    - [ ] release notes are up-to-date on develop
    - [ ] release-x.x.x branch created: `git checkout develop | git pull | git checkout -b release-x.x.x`
    - [ ] _on release-x.x.x branch:_ version bump
    - [ ] _on release-x.x.x branch:_ releasenotes_develop.md renamed to releasenotes_**Vx.x.x**.md
    - [ ] _on release-x.x.x branch:_ image tag in ./config/_service.yaml_ updated from **latest** to **[x.x.x].latest**
    - [ ] changes pushed to release branch: `git push` > Travis built image > see [DockerHub](https://cloud.docker.com/u/keptn/repository/list)

  **end**

---
### Phase 2 - Release of keptn core

**foreach:**
- [ ] control > **control:0.2.4.latest**
- [ ] authenticator > **authenticator:0.2.3.latest**
- [ ] eventbroker > **eventbroker:0.2.3.latest**
- [ ] eventbroker-ext > **eventbroker-ext:0.2.3.latest**
- [ ] bridge > **bridge:0.1.2.latest**

  **begin**

    - [ ] all feature/bugfix/hotfix branches merged into develop
    - [ ] inactive branches deleted
    - [ ] release notes are up-to-date on develop
    - [ ] release-x.x.x branch created: `git checkout develop | git pull | git checkout -b release-x.x.x`
    - [ ] _on release-x.x.x branch:_ version bump
    - [ ] _on release-x.x.x branch:_ releasenotes_develop.md renamed to releasenotes_**Vx.x.x**.md
    - [ ] _on release-x.x.x branch:_ image tag in ./config/_service.yaml_ updated from **latest** to **[x.x.x].latest**
    - [ ] changes pushed to release branch: `git push` > Travis built image > see [DockerHub](https://cloud.docker.com/u/keptn/repository/list)

  **end**

---
### Phase 3 - Release of keptn installer
- [ ] upgrade script from keptn 0.2.x to keptn 0.3.0 available
- [ ] all feature/bugfix/hotfix branches merged into develop
- [ ] inactive branches deleted
- [ ] release notes are up-to-date on develop
- [ ] release-x.x.x branch created: `git checkout develop | git pull | git checkout -b release-x.x.x`
- [ ] _on release-x.x.x branch:_ version bump 
- [ ] _on release-x.x.x branch:_ releasenotes_develop.md renamed to releasenotes_**Vx.x.x**.md
- [ ] _on release-x.x.x branch:_ wearUniform.sh updated, i.e., reference to **release-x.x.x** branch
- [ ] _on release-x.x.x branch:_ setupKeptn.sh updated, i.e., env variables reference **release-x.x.x** branch
- [ ] _on release-x.x.x branch:_ deployDynatrace.sh updated, i.e., reference to **release-x.x.x** branch
- [ ] _on release-x.x.x branch:_ installer.yaml updated, i.e., reference to **installer:0.x.x.latest**
- [ ] changes pushed to release branch: `git push` > Travis built image > see [DockerHub](https://cloud.docker.com/u/keptn/repository/list)

Result: **installer:0.3.0.latest**

---
### Phase 4 - Release of keptn cli
- [ ] all feature/bugfix/hotfix branches merged into develop
- [ ] release notes are up-to-date on develop
- [ ] README.md is up-to-date on develop
- [ ] release-x.x.x branch created: `git checkout develop | git pull | git checkout -b release-x.x.x`
- [ ] _on release-x.x.x branch:_ version bump 
- [ ] _on release-x.x.x branch:_ releasenotes_develop.md renamed to releasenotes_**Vx.x.x**.md
- [ ] changes pushed to release branch: `git push` > Travis built image > see [Storage](https://console.cloud.google.com/storage/browser/keptn-cli?project=sai-research)

Result: **keptn:0.3.0.latest** CLI

---
### Phase 5 - Preparation phase
- [ ] keptn.sh/docs is up-to-date
- [ ] keptn/examples released > **0.3.0**

---
### Phase 6 - Test phase
- [ ] upgrade script tested
- [ ] installation according to docs except for `keptn install` command - additionally specify `--keptn-version=release-0.3.0 -p=<openshift|gke|aks>`
  - [ ] use **keptn:0.x.x.latest** CLI Windows
  - [ ] use **keptn:0.x.x.latest** CLI MacOS
  - [ ] use **keptn:0.x.x.latest** CLI Linux
- [ ] use cases according to docs are successfully executed
  - [ ] without monitoring
  - [ ] with prometheus
  - [ ] with dynatrace

---
### Official release of services and core - 3 ...
**foreach:**
- [ ] github-service > **github-service:0.2.2**
- [ ] servicenow-service > **servicenow-service:0.1.2**
- [ ] pitometer-service > **pitometer-service:0.1.3**
- [ ] dynatrace-service > **dynatrace-service:0.1.2**
- [ ] jmeter-service > **jmeter-service:0.1.0**
- [ ] helm-service > **helm-service:0.1.0**
- [ ] gatekeeper-service > **gatekeeper-service:0.1.0**
- [ ] openshift-route-service > **openshift-route-service:0.1.0**
- [ ] authenticator  > **authenticator:0.2.3**
- [ ] bridge > **bridge:0.1.2**
- [ ] control > **control:0.2.4**
- [ ] eventbroker > **eventbroker:0.2.3**
- [ ] eventbroker-ext > **eventbroker-ext:0.2.3**

  **begin**

    - [ ] check if all PRs are merged
    - [ ] _on release-x.x.x branch:_ image tag in ./config/_service.yaml_ updated from **[x.x.x].latest** to **[x.x.x]**
    - [ ] PR from release-x.x.x to master
    - [ ] Travis built image > see [DockerHub](https://cloud.docker.com/u/keptn/repository/list)
    - [ ] service on GitHub released based on release notes
    - [ ] master branch tagged
    - [ ] new (empty) release notes (releasenotes_develop.md) file on develop branch

  **end**

---
### Official release of installer - 2 ...
- [ ] _on release-x.x.x branch:_ wearUniform.sh updated, i.e., reference to **tag**
- [ ] _on release-x.x.x branch:_ setupKeptn.sh updated, i.e., env variables reference to **tag**
- [ ] _on release-x.x.x branch:_ deployDynatrace.sh updated, i.e., reference to **tag** 
- [ ] _on release-x.x.x branch:_ upgradeKeptn.sh updated, i.e., reference to **tag** 
- [ ] _on release-x.x.x branch:_ ./manifests/installer/installer.yaml updated, i.e., reference to **tag** 
- [ ] PR from release-x.x.x to master
- [ ] Travis built image > see [DockerHub](https://cloud.docker.com/u/keptn/repository/list)
- [ ] installer on GitHub released based on release notes
- [ ] master branch tagged
- [ ] new (empty) release notes (releasenotes_develop.md) file on develop branch

Result: **installer:0.x.x.**

---
### Official release of keptn - 1 ... go.
- [ ] PR from release-x.x.x to master
- [ ] Travis built image > see [Storage](https://console.cloud.google.com/storage/browser/keptn-cli?project=sai-research)
- [ ] release keptn on GitHub based on release notes (upload keptn cli for mac, linux, windows)
- [ ] master branch tagged
- [ ] new (empty) release notes (releasenotes_develop.md) file on develop branch
