### ISSUE TITLE
Bridge: Research - Replace highcharts with different library to remove vulnerable dependency

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#4909]
Related Snyk PR: https://github.com/keptn/keptn/pull/3177
Related Dependabot PR: https://github.com/keptn/keptn/pull/3998

In order to get rid of the security vulnerability from highcharts, we should consider replacing highcharts with a different library.
As highcharts is only used for visualizing evaluation results, it should be safe to replace it without causing build errors.

### TODO
- [x] Identify library features that we use and have to be available in the other library e.g. compared events (2 overlay bars)
- [x] Research for a suitable alternative library
- [x] Research, if highcharts can be replaced/removed from the components and if some other dependencies exist within the component
- [x] If the research outcome supports replacing the library, create a new issue with explicit tasks to do so

# Deliverable
- [x] Proof of concept that showcases how the new library can be used in the Bridge
- [x] Document the reasons why we cannot use Highcharts

**Comment by thisthat** [comment]
We decided to sandbox the research to two days

**Comment by Kirdock** [comment]
Option 1: ApexCharts.

What is not possible or only partly supported:
1. It is impossible to set the right color for fail, success, and warning because of its shading algorithm.
2. Secondary highlight: It's somehow possible with `annotations`, but it seems like that the right position can't be set for heatmaps (the effect starts in the middle of the tile; so an offset by 50% of a tile)
3. Selection: Haven't found a way to select a column instead of a single tile/cell. It could be done with annotations instead but here we have the problem mentioned in 2.
4. Tooltip: more or less. For a custom tooltip, custom HTML has to be assigned as a string to the chart.
