### ISSUE TITLE
Adapt project polling for all screens

### ISSUE THREAD

**Issue by Kirdock** [keptn/keptn#4920]
The polling result of the project is not used in every view and some views only require one information of the project instead of the whole one.

- Environment Screen: Nearly everything is useful here. Does not need any adjustments.
- Sequence Screen: Only requires the latest deployment of a service in a stage. This information is used for the approval-trace. There the currently deployed artifact is shown.
- Service Screen (should be changed with #4918): Only needs the services of each stage and the latest deployment information.
- Settings Screen: Does not need any polling and only Git-related data.
- Integrations and Uniform screen: They don't need the project

## Open Question
Is git data only stored in the beginning or is it changed somewhere else? 

# Tracking issues
- [x] https://github.com/keptn/keptn/issues/5098
- [x] https://github.com/keptn/keptn/issues/5099
- [x] https://github.com/keptn/keptn/issues/5100
- [x] https://github.com/keptn/keptn/issues/5101
- [x] https://github.com/keptn/keptn/issues/5246
- [x] https://github.com/keptn/keptn/issues/7796
- [x] #7799 
- [x] #7798 
- [x] #7797 
- [x] #7804 
- [x] #7800 
- [x] #7802

**Comment by thisthat** [comment]
This issue has been split into:
- [ ] tbd

**Comment by agrimmer** [comment]
Can you please explain what you mean with "Is git data only stored in the beginning or is it changed somewhere else?"?

**Comment by thisthat** [comment]
All issues have been merged!
