### ISSUE TITLE
Provide keptn support for PKS (Pivotal/VMWare)

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/keptn#5]
To close this issue, following tasks need to be completed: 

Documentation on keptn.sh:
- [x] #439 Restructuring the keptn install instructions for cross-platform support
- [x] #440 Provide instructions to create a PKS cluster

CLI / Installer support:
- [x] #436 Extend keptn CLI to support different platforms for keptn install
- [x] #4 Provide keptn support for Openshift (Florian is restructuring the scripts in keptn/installer. His PR also provides the features to support PKS as target platform. https://github.com/keptn/installer/tree/feature/4/openshift-support)

Testing the new feature:
- [x] `keptn install -p=pks`

**Comment by johannes-b** [comment]
Installation process: 

- the keptn/installer repos has a branch: **feature/5/install-pks**
- the branch **feature/5/install-pks** was used to install keptn on the PKS cluster: my-cluster
    - added the property "gclouduser" to the creds.json file 
         - "gclouduser": "johannes.braeuer@dynatrace.com"
    - executed: `./installKepnt.sh`

Current status:

- `keptn auth` works, meaning that we can connect to the keptn control component
- `keptn configure` fails. The reason is that Knative evening does not work. Even though the control component receives the event and sends it to the keptn-channel, the dispatcher in the knative-eventing namespace does not forward it. 

Next step:

- We need to get Knative eventing running.

**Comment by johannes-b** [comment]
Hmm, after re-installing Istio and Knative, the dispatcher now receives the event. 

However, it runs into an error: 
```
{"level":"info","ts":1559908738.6197615,"caller":"provisioners/message_receiver.go:118","msg":"Received request for keptn-channel.keptn.channels.cluster.local"}
{"level":"info","ts":1559908738.6199577,"caller":"provisioners/message_dispatcher.go:104","msg":"Dispatching message to http://github-service.keptn.svc.cluster.local/"}
{"level":"error","ts":1559908768.6204684,"caller":"fanout/fanout_handler.go:118","msg":"Fanout had an error","error":"Unable to complete request Post http://github-service.keptn.svc.cluster.local/: dial tcp 10.100.200.24:80: i/o timeout","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:118\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:96\ngithub.com/knative/eventing/pkg/provisioners.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/provisioners/message_receiver.go:134\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:101\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:128\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:105\nnet/http.serverHandler.ServeHTTP\n\t/root/sdk/go1.12rc1/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/root/sdk/go1.12rc1/src/net/http/server.go:1878"}
```

Instructions to address this problem are provided here: https://knative.dev/v0.4-docs/eventing/debugging/  at the end of the page. 

I will continue working on that on Tuesday.

**Comment by johannes-b** [comment]
The issue is that the isio-proxy is missing. [see](https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_eventing/917/pull-knative-eventing-integration-tests/1107750127247822848/)

Now I try it with Istio 1.0.6

**Comment by johannes-b** [comment]
Summary:

* checkout branch: `feature/5/install-pks`
* go to `./install/scripts/`
* provide a creds.json with values for (1), (2), (3), (4) and (5):
  ```
  {
    "jenkinsUser": "admin",
    "jenkinsPassword": "AiTx4u8VyUV8tCKk",
    "githubUserName": "**(1)**",
    "githubPersonalAccessToken": "**(2)**",
    "githubUserEmail": "**(3)**",
    "githubOrg": "**(4)**",
    "clusteripv4cidr": "10.200.0.0/16",
    "serveripv4cidr": "10.100.200.0/24",
    "gclouduser": "**(5)**"
  }
  ```
* execute `./installKeptn.sh`
* go to your Jenkins and click the *Save* button as explained at point [Important](https://keptn.sh/docs/0.2.2/installation/setup-keptn-gke/#install-keptn)

**Note** If it fails due to following error: 
```
error: unable to recognize "https://github.com/knative/serving/releases/download/v0.4.0/serving.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
[keptn|ERROR] [2019-06-11 15:12:19] Applying knative serving components failed.
[keptn|ERROR] [2019-06-11 15:12:19] Stopping keptn installation. Already created resources are not deleted; execute the uninstallKeptn.sh script to clean-up.
```
then comment out the line `kubectl create clusterrolebinding keptn-cluster-admin-binding --clusterrole=cluster-admin --user=$GCLOUD_USER` in `./installKeptn.sh` and re-run the `./installKeptn.sh` script.

**Note** If helm-service runs into the error: `Error: Unauthorized`
then delete tiller-deploy pod: 
```
kubectl get pods -n kube-system
kubectl delete pod tiller-deploy-xxxxx-xxxxx -n kube-system
```
