### ISSUE TITLE
Zero Downtime

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5301]
## Research
- [x] https://github.com/keptn/keptn/issues/4182
- [x] https://github.com/keptn/keptn/issues/6179
- [x] https://github.com/keptn/keptn/issues/6231
- [x] https://github.com/keptn/keptn/issues/6232
- [x] https://github.com/keptn/keptn/issues/6230
- [x] https://github.com/keptn/keptn/issues/6229
- [x] https://github.com/keptn/keptn/issues/6602

## Core
- [x] https://github.com/keptn/keptn/issues/4525
- [x] https://github.com/keptn/keptn/issues/6397
- [x] https://github.com/keptn/keptn/issues/6349
- [x] https://github.com/keptn/keptn/issues/6348
- [x] https://github.com/keptn/keptn/issues/6346
- [x] https://github.com/keptn/keptn/issues/6347
- [x] https://github.com/keptn/keptn/issues/6308
- [x] https://github.com/keptn/keptn/issues/5147
- [x] https://github.com/keptn/keptn/issues/6306
- [x] https://github.com/keptn/keptn/issues/6345
- [x] https://github.com/keptn/keptn/issues/4522
- [x] https://github.com/keptn/keptn/issues/5991
- [x] https://github.com/keptn/keptn/issues/5304
- [x] https://github.com/keptn/keptn/issues/5303
- [x] https://github.com/keptn/keptn/issues/5369
- [x] https://github.com/keptn/keptn/issues/4526
- [x] https://github.com/keptn/keptn/issues/4518
- [x] https://github.com/keptn/keptn/issues/7435
- [x] https://github.com/keptn/keptn/issues/7434

## Bridge
- [x] https://github.com/keptn/keptn/issues/6307
- [x] https://github.com/keptn/keptn/issues/6323
- [x] https://github.com/keptn/keptn/issues/6219
- [x] https://github.com/keptn/keptn/issues/6218
- [x] https://github.com/keptn/keptn/issues/6217
