### ISSUE TITLE
Configuration Service: Evaluate branching strategy for representing stages

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#6230]
Right now, each stage within a Keptn project is represented by a branch in the project's git repository. This leads to performance problems when requesting resources for different branches, since we need to check out the correlating branch first. The goal of this issue is to determine whether we can represent the stages of a project differently, e.g. as different directories within the same branch, e.g.:

```
sockshop
  -> dev # stage directory
    -> carts # service directory
    -> carts-db # service directory
  -> staging # stage directory
    -> carts # service directory
    -> carts-db # service directory
```

## Tasks:

- [ ] Find and document a more efficient approach of representing stages within the git repo
- [ ] PoC with performance analysis for the configuration service response times
- [ ] Document where we need to adapt to the changes
- [ ] Define a migration strategy

**Comment by bacherfl** [comment]
The proposed change in the representation of stages within a project has been evaluated in the following draft PR: https://github.com/keptn/keptn/pull/6301

# Performance Results

To see whether the proposed solution also yields advantages in terms of performance, I conducted a very simple experiment where I periodically triggered evaluations for a service in different stages:

```
while true; do keptn trigger evaluation --project=sockshop-baseline --stage=staging --service=carts --timeframe=5m && keptn trigger evaluation --project=sockshop-baseline --stage=dev --service=carts --timeframe=5m; sleep 5; done
```

The project used for that experiment was connected to an upstream repository on Github

The resulting response times were as follows:

*Current approach with branches for stages:*
![Screenshot 2021-12-14 at 16 50 18](https://user-images.githubusercontent.com/2143586/146032100-13ce8bc2-9983-49ee-aeed-defb6f3b4995.png

*Directory based stages:*
![Screenshot 2021-12-14 at 16 46 06](https://user-images.githubusercontent.com/2143586/146031932-14e84145-0452-4868-941a-d7945b187487.png)


The results suggest that storing stages as directories, as opposed to branches will yield an improvement in terms of performance. This is expected because it's not required to check out branches during  a resource retrieval.

However, a significantly bigger performance boost is expected for the concept proposed in https://github.com/keptn/keptn/issues/6231
