### ISSUE TITLE
Task Sequence execution based on upstream repository commit ID

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#6231]
Currently, services that perform tasks during a task sequence might request certain resources from the configuration service, such as:

- shipyard controller: shipyard.yaml
- lighthouse service: slo.yaml
- dynatrace-service: sli.yaml
- ...

Right now, the configuration service always retrieves the latest version for all resources which causes a lot of requests to the upstream repository, which is a problem in terms of rate limits.
To mitigate this, a sequence execution could be performed in the context of a certain commit ID - this way, all services involved in a task execution should request their resources for a certain git commit ID, which the configuration service will have in its local git history after pulling the changes once from the upstream repository. To enable this, the following questions need to be answered:

## Tasks

- [x] Document all places where services request resources from the configuration-service during a task sequence
- [x] Research how we can propagate the git commit ID throughout a sequence (e.g. In the context of the CloudEvents, i.e. next to `shkeptncontext`, `triggeredid`, etc.)
- [x] Document all places where we need to adapt to these changes
- [x] How do we actually pass the commit ID when triggering a sequence (e.g. either user defined, or the shipyard controller uses the latest commit ID after fetching the shipyard.yaml for the first time after a sequence has been triggered). Also, how do we do this for sequences spanning multiple stages, since we have different commit histories for each branch representing a stage (this depends on the results of #6230 )? 
- [x] How do we handle the case where services are writing to the upstream repository (e.g. helm-service) - should those be able to override the existing commit ID and pass the new one to subsequent events?
- [x] PoC with performance analysis for the configuration service response times

## Ideas

Map commit id to shctx and store it in the DB. This way, we could reduce the size of the events 

## DoD

- [x] All aforementioned tasks are documented as a comment to this issue

**Comment by RealAnna** [comment]
-----------------------------------------------------------------------------------------------------------

I run a few test with the **old configuration service**:
![image](https://user-images.githubusercontent.com/89971034/149926713-4187bb9d-5555-4b32-9b91-a7cbb3a725a3.png)
mean response time for one or two request is constantly around 600ms, this tends to degradate pretty quickly: for around 30 request of the same resource the delay is up to 2 seconds! More than  that and the monitoring tools declare a "Response time degradation" 
![image](https://user-images.githubusercontent.com/89971034/149928343-efc2ac35-cb91-465a-952d-a57cd24b9142.png)

-----------------------------------------------------------------------------------------------------------

After I executed identical tests on the **new service** exploiting git commit for retrieval:

![image](https://user-images.githubusercontent.com/89971034/149927374-db19bdeb-0224-4097-bfbf-a0c3a96da946.png)

If we check the left side of graph in case of first retrieval we have around 210 ms delay but from then on we lower at 100ms or less.  **Service could easily handle  260 requests with a third of the time per request of the old version.**  

![image](https://user-images.githubusercontent.com/89971034/149927875-b6309cfc-47cc-4c3c-adfa-db8bb1db9e0e.png)
-----------------------------------------------------------------------------------------------------------
