### ISSUE TITLE
Subscribe shipyard controller to NATS via Jetstream

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#6685]
The goal of this issue is to enable the shipyard controller to receive incoming CloudEvents using a pull based Nats Jetstream subscription, which will have the advantage of achieving an exactly-once message delivery guarantee for the shipyard controller.

A proof of concept of this is already done in the following draft PR: https://github.com/keptn/keptn/pull/6631 

In this PR, the subscription to Nats is happening in a component of the shipyard controller, instead of the distributor. The reason for that is to not add yet another way of subscribing to events to the distributor. The Jetstream subscription handling should be provided as a component of the go-utils to have the possibility of re-using it in other services and integrations. However, using Jetstream is for now only planned for the shipyard controller. 

**Tasks:**

- [ ] Create component for connecting to Jetstream in go-utils (#6631 can be used as a reference)
- [ ] Use that component in the shipyard controller to subscribe to Jetstream
- [ ] Upgrade helm-chart of NATs
- [ ] The feature should be implemented directly inside the shipyard-controller

**Definition of Done:**

- [ ] The shipyard controller receives messages via Jetstream
- [ ] When a message is sent to Keptn via the API and the shipyard controller is currently not available, the message will be received and handled by the shipyard controller as soon as it is up again
- [ ] Integration test (The graceful shutdown integration test potentially covers this, but a dedicated test that guarantees that the shipyard controller is not there when a message is sent would be even better)

**Comment by agrimmer** [comment]
I would like to understand better why you proposed to put the JetStream logic into the go-utils instead of the distributor. My questions are:
- Could other services like the dynatrace-service reuse this functionality if we would have this logic implemented in the distributor?
- Are we aware that then integrations like the dynatrace-service has a dependency on NATS Jetstream?

**Comment by thisthat** [comment]
IMHO the distributor is too beefy and overloaded with responsibilities. I would envision the distributor to be the "glue code" for a remote execution plane. For integrations/services that want to talk with Keptn and are inside the same "local" execution plane, we could simplify their deployment and resource requirements by using the `go-utils` code without the need of the distributor.

**Comment by trauter** [comment]
I like the strategy to make the distributor more simple in the long run. Eventually, I guess that execution plane components should provide feature-parity for local and remote deployments (at least for services that are meant to be executed remotely). 
Adding even more functionalities that only work locally (jetstream features) to the distributor would even increase the gap between local and remote execution planes.

At the same time, having a pure "backend/control-plane" communication library (e.g. in go-utils?) would clear the path to make the distributor an execution-plane-only component (as Giovanni pointed out). I guess this separation of concerns would also help to make the distributor  less "beefy" ;).
So in general I really like the approach.

One remark (as already discussed): Be careful with the "exactly once" feature: It sounds nice, but typically 
- it's way more expensive compared to "at least once", and
- if you do not ensure "exactly once" over the whole message path (e.g. remote execution plane service => REST API => api-service => NATS => shipyard => another remote execution service), it will not even help if you rely on the jetstream feature.

Therefore, many times it's easier to use at-least-once and ensure idempotency where it's needed (e.g. in the shipyard controller).
I am not deep enough into Keptn to know what's best in this specific case, but I wanted to trigger some thinking on your side :)
