### ISSUE TITLE
Introduce modules for components in Bridge

### ISSUE THREAD

**Issue by ermin-muratovic** [keptn/keptn#7932]
# Technical Details

At the moment the Bridge has one root NgModule named `AppModule`, which contains all views, components, service providers and other code files.

We should introduce modules for our components, to allow code sharing and reuse code e.g. for a demo application. Introducing modules makes the application also tidier and allows to reduce application size and improve application performance by enabling lazy-loading.

In the first step we should introduce modules for our components. The PR #7897 should serve as a template.

Following modules should be introduced, containing the documented components, in this order:

- [x] `ktb-loading.module` with `ktb-loading-spinner.component` and `ktb-loading-distractor.component`
     - @heinzburgstaller #8048 
- [x] `ktb-confirmation-dialog.module` with `ktb-confirmation-dialog.component`
     - @ermin-muratovic #8058 
- [x] `ktb-delete-confirmation.module` with `ktb-delete-confirmation.component`
    -  @heinzburgstaller #8077 
- [x] `ktb-deletion-dialog.module` with `ktb-deletion-dialog.component`
     - @heinzburgstaller #8060 
- [x] `ktb-sli-breakdown.module` with `ktb-sli-breakdown.component` and `ktb-sli-breakdown-criteria-item.component`
     - @heinzburgstaller #8062  
- [x] `ktb-evaluation-details.module` with `ktb-evaluation-details.component`
     - @ermin-muratovic #8066 
- [x] `ktb-approval-item.module` with `ktb-approval-item.component`
     - @heinzburgstaller  #8069 
- [x] `ktb-drag-and-drop.module` with `ktb-drag-and-drop.directive`
     - @ermin-muratovic #8071 
- [x] `ktb-certificate-input.module` with `ktb-certificate-input.component`
     - @ermin-muratovic #8071 
- [x] `ktb-copy-to-clipboard.module` with `ktb-copy-to-clipboard.component`
     - @heinzburgstaller #8072
- [x] `ktb-create-secret-form.module` with `ktb-create-secret-form.component`
     - @heinzburgstaller #8077
- [x] `ktb-create-service.module` with `ktb-create-service.component`
     -  @heinzburgstaller #8073 
- [x] `ktb-danger-zone.module` with `ktb-danger-zone.component`
     - @heinzburgstaller #8077
- [x] `ktb-date-input.module` with `ktb-datetime-picker.component` and `ktb-time-input.component`
     - @heinzburgstaller #8077
- [x] `ktb-deployment-list.module` with `ktb-deployment-list.component`
     - @heinzburgstaller #8077
- [x] `ktb-evaluation-info.module` with `ktb-evaluation-info.component`
     - @heinzburgstaller #8077
- [x] `ktb-stage-badge.module` with `ktb-stage-badge.component`
     - @heinzburgstaller #8077
- [x] `ktb-deployment-stage-timeline.module` with `ktb-deployment-stage-timeline.component`
     - @ermin-muratovic #8091 
- [x] `ktb-edit-service.module` with `ktb-edit-service.component` and `ktb-edit-service-file-list.component`
     - @ermin-muratovic #8091 
- [x] `ktb-selectable-tile.module` with `ktb-selectable-tile.component`
     - @ermin-muratovic #8091 
- [x] `ktb-event-item.module` with `ktb-event-item.component`
     - @ermin-muratovic #8091 
- [x] `ktb-expandable-tile.module` with `ktb-expandable-tile.component`
     - @ermin-muratovic #8091 
- [x] `ktb-heatmap.module` with `ktb-heatmap.component`, `ktb-heatmap-tooltip.component` and `ktb-heatmap-utils`
     - @Kirdock #7658 
- [x] ~~`ktb-horizontal-separator.module` with `ktb-horizontal-separator.component`~~
     - not used and can be deleted #8125 
- [x] `ktb-subscription-item.module` with `ktb-subscription-item.component`
     - @ermin-muratovic #8125 
- [x] `ktb-uniform-subscriptions.module` with `ktb-uniform-subscriptions.component`
     - @ermin-muratovic #8125 
- [x] `ktb-uniform-registration-logs.module` with `ktb-uniform-registration-logs.component`
     - @ermin-muratovic #8125 
- [x] `ktb-keptn-services-list.module` with `ktb-keptn-services-list.component`
     - @ermin-muratovic #8125 
- [ ] ~~`ktb-markdown.module` with `ktb-markdown.component`~~
     - not used and will be deleted with #8057
- [x] `ktb-payload-viewer.module` with `ktb-payload-viewer.component`
     - @ermin-muratovic #8125 
- [x] `ktb-tree-list-select.module` with `ktb-tree-list-select.component`
     - @ermin-muratovic #8125 
- [x] `ktb-variable-selector.module` with `ktb-variable-selector.component`
     - @ermin-muratovic #8125 
- [x] `ktb-webhook-settings.module` with `ktb-webhook-settings.component`
     - @ermin-muratovic #8125 
- [x] `ktb-modify-uniform-subscription.module` with `ktb-modify-uniform-subscription.component`
     - @ermin-muratovic #8125 
- [x] `ktb-no-service-info.module` with `ktb-no-service-info.component`
     - @ermin-muratovic #8125 
- [x] `ktb-notification.module` with `ktb-notification.component` and `ktb-notification-bar.component`
     - @ermin-muratovic #7897 
- [x] `ktb-sequence-state-info.module` with `ktb-sequence-state-info.component`
     - @renepanzar #8119
- [x] `ktb-sequence-state-list.module` with `ktb-sequence-state-list.component`
     - @renepanzar #8119
- [x] `ktb-project-list.module` with `ktb-project-list.component` and `ktb-project-tile.component`
     - @renepanzar #8119
- [x] `ktb-error-view.module` with `ktb-error-view.component`
     - @renepanzar #8119
- [x] `ktb-integer-input.module` with `ktb-integer-input.directive`
     - @renepanzar #8119
- [x] `ktb-proxy-input.module` with `ktb-proxy-input.component`
     - @renepanzar #8127 
- [x] `ktb-ssh-key-input.module` with `ktb-ssh-key-input.component`
     - @renepanzar #8127 
- [x] `ktb-project-settings.module` with `ktb-project-settings.component`, `ktb-project-settings-git.component`, `ktb-project-settings-git-extended.component`, `ktb-project-settings-git-https.component`, `ktb-project-settings-git-ssh.component`, `ktb-project-settings-git-ssh-input.component`, `ktb-project-settings-shipyard.component` and `ktb-project-create-message.component`
     - @renepanzar #8127 
- [x] `ktb-sequence-controls.module` with `ktb-sequence-controls.component`
     - @renepanzar #8139
- [x] `ktb-root-events-list.module` with `ktb-root-events-list.component`
     - @renepanzar #8139
- [x] `ktb-secrets-list.module` with `ktb-secrets-list.component`
     - @renepanzar #8139
- [x] `ktb-sequence-list.module` with `ktb-sequence-list.component`
     - @renepanzar #8139
- [x] `ktb-sequence-tasks-list.module` with `ktb-sequence-tasks-list.component` and `ktb-task-item.component`
     - @renepanzar #8139
- [x] `ktb-sequence-timeline.module` with `ktb-sequence-timeline.component`
     - @renepanzar #8153
- [x] `ktb-service-details.module` with `ktb-service-details.component`
     - @renepanzar #8153
- [x] `ktb-service-settings.module` with `ktb-service-settings.component`, `ktb-service-settings-list.component` and `ktb-service-settings-overview.component`
     - @renepanzar #8153
- [x] `ktb-services-list.module` with `ktb-services-list.component`
     - @renepanzar #8153
- [x] `ktb-stage-details.module` with `ktb-stage-details.component` @Kirdock  #8158
- [x] `ktb-trigger-sequence.module` with `ktb-trigger-sequence.component` @Kirdock #8158
- [x] `ktb-stage-overview.module` with `ktb-stage-overview.component` @Kirdock #8158
- [x] `ktb-user.module` with `ktb-user.component` @Kirdock #8158

# Acceptance Criteria

- [x] Components are in separate modules
- [ ] App Module is cleaned up (`dtModules` and `ktbModules` which are not used should be removed)
- [x] Unit tests are adjusted

# DoD

- [ ] Acceptance criteria are met
